"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_custom_400)\
$os\
$username\
[](bg:color_custom_500 fg:color_custom_400)\
$directory\
[](fg:color_custom_500 bg:color_custom_600)\
$git_branch\
$git_status\
[](fg:color_custom_600 bg:color_custom_700)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_custom_700 bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_custom_100 = '#FFFFD9'
color_custom_200 = '#FFD5A3'
color_custom_300 = '#F89433'
color_custom_400 = '#E46B34'
color_custom_500 = '#AB4232'
color_custom_600 = '#68202E'
color_custom_700 = '#3A1527'
color_custom_800 = '#211023'

[os]
disabled = false
style = "bg:color_custom_400 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_custom_400 fg:color_fg0"
style_root = "bg:color_custom_400 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_custom_500"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_custom_600"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_custom_600)]($style)'

[git_status]
style = "bg:color_custom_600"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_custom_600)]($style)'

[nodejs]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[c]
symbol = " "
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[rust]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[golang]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[php]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[java]
symbol = " "
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[kotlin]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[haskell]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[python]
symbol = ""
style = "bg:color_custom_700"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_custom_700)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_custom_500)'